In [3]:
import pandas as pd

In [4]:
metadata = pd.read_csv('../data/joined.csv', index_col=0)
metadata

/tmp/ipykernel_90384/3173754459.py:1: DtypeWarning: Columns (28,29,30,49,51,54,55,56,57,59,60,61,62,63,65,66,67,71,72,73,74,75,76,78,79,80,81,82,83,84,85,87,88,89,91,92,93,94,96,98,99,100,102,103,104,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,135,136,137,138,139,140,141,142,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,162,163,164,166,167,168,169,170,171,172,173,174,175,176,177,179,180,182,183,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata = pd.read_csv('../data/joined.csv', index_col=0)

,acc,assay_type,center_name,consent,experiment,sample_name,instrument,librarylayout,libraryselection,librarysource,...,er_gfp_sam,subsrc_note_sam_s_dpl392,authors_sam,env_biome_sam,title,Identifiers,Organism,Attributes,Accession,ID
biosample,,,,,,,,,,,,,,,,,,,,,
SAMD00025071,DRR029571,RNA-Seq,NUGSS,public,DRX026629,DRS020767,Illumina Genome Analyzer IIx,SINGLE,RANDOM,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Error: uid 25071 cannot get document summary,NaN,NaN,NaN,NaN,NaN
SAMD00025072,DRR029572,RNA-Seq,NUGSS,public,DRX026630,DRS020768,Illumina Genome Analyzer IIx,SINGLE,RANDOM,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Error: uid 25072 cannot get document summary,NaN,NaN,NaN,NaN,NaN
SAMD00025073,DRR029573,RNA-Seq,NUGSS,public,DRX026631,DRS020769,Illumina Genome Analyzer IIx,SINGLE,RANDOM,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Error: uid 25073 cannot get document summary,NaN,NaN,NaN,NaN,NaN
SAMD00025074,DRR029574,RNA-Seq,NUGSS,public,DRX026632,DRS020770,Illumina Genome Analyzer IIx,SINGLE,RANDOM,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Error: uid 25074 cannot get document summary,NaN,NaN,NaN,NaN,NaN
SAMD00025075,DRR029575,RNA-Seq,NUGSS,public,DRX026633,DRS020771,Illumina Genome Analyzer IIx,SINGLE,RANDOM,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Error: uid 25075 cannot get document summary,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAMN41829221,SRR29409034,RNA-Seq,KANSAS STATE UNIVERSITY,public,SRX24922515,Soybean308,NextSeq 500,SINGLE,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Plant sample from Glycine max,"{'BioSample': 'SAMN41829221', 'Sample name': '...",Glycine max,"{'cultivar': 'Pharaoh', 'tissue': 'Stem'}",SAMN41829221,41829221.0
SAMN41829222,SRR29409033,RNA-Seq,KANSAS STATE UNIVERSITY,public,SRX24922516,Soybean309,NextSeq 500,SINGLE,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Plant sample from Glycine max,"{'BioSample': 'SAMN41829222', 'Sample name': '...",Glycine max,"{'cultivar': 'Pharaoh', 'tissue': 'Stem'}",SAMN41829222,41829222.0
SAMN41829223,SRR29409032,RNA-Seq,KANSAS STATE UNIVERSITY,public,SRX24922517,Soybean310,NextSeq 500,SINGLE,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Plant sample from Glycine max,"{'BioSample': 'SAMN41829223', 'Sample name': '...",Glycine max,"{'cultivar': 'Pharaoh', 'tissue': 'Stem'}",SAMN41829223,41829223.0
SAMN41829224,SRR29409031,RNA-Seq,KANSAS STATE UNIVERSITY,public,SRX24922518,Soybean311,NextSeq 500,SINGLE,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Plant sample from Glycine max,"{'BioSample': 'SAMN41829224', 'Sample name': '...",Glycine max,"{'cultivar': 'Dt974290', 'tissue': 'Stem'}",SAMN41829224,41829224.0
SAMN41829225,SRR29409030,RNA-Seq,KANSAS STATE UNIVERSITY,public,SRX24922519,Soybean312,NextSeq 500,SINGLE,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,NaN,NaN,Plant sample from Glycine max,"{'BioSample': 'SAMN41829225', 'Sample name': '...",Glycine max,"{'cultivar': 'Dt974290', 'tissue': 'Stem'}",SAMN41829225,41829225.0

In [5]:
def matching_cols(row, pat):
    return row[row.astype(str).str.contains(pat, regex=False, case=False).fillna(False)].to_dict()

Junto palabras clave en kws. Guardo ```{columna: valor}``` en ```estreses``` si la columna contiene la palabra clave en su valor.

In [6]:
kws = ['control', 'ctrl', 'stress', 'drought', 'bacteria', 'inoculated', 'flood', 'deficit', 'infest', 'pathogen', 'acid', 'fung', 'sporus']
estreses = pd.DataFrame(index = metadata.index)

for kw in kws:
    estreses[kw] = metadata.apply(lambda r: matching_cols(r, kw), axis=1)

In [7]:
indicadores = estreses.map(lambda v: v != {})
indicadores

,control,ctrl,stress,drought,bacteria,inoculated,flood,deficit,infest,pathogen,acid,fung,sporus
biosample,,,,,,,,,,,,,
SAMD00025071,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMD00025072,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMD00025073,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMD00025074,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMD00025075,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAMN41829221,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN41829222,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN41829223,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN41829224,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN41829225,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
indicadores.sum(axis=0)

control       441
ctrl           13
stress        485
drought        84
bacteria        0
inoculated    339
flood           0
deficit       135
infest        141
pathogen        3
acid           79
fung           12
sporus          9
dtype: int64

In [9]:
indicadores.sum(axis=1)

biosample
SAMD00025071    0
SAMD00025072    0
SAMD00025073    0
SAMD00025074    0
SAMD00025075    0
               ..
SAMN41829221    0
SAMN41829222    0
SAMN41829223    0
SAMN41829224    0
SAMN41829225    0
Length: 10992, dtype: int64

In [10]:
estreses = estreses[indicadores.sum(axis=1) > 0]
indicadores = indicadores.loc[estreses.index]
estreses.to_csv('estreses.csv')

# Condición
## Estres vs. control

In [11]:
def cols_true(row):
# Devuelve lista de columnas verdaderas para row
    return row[row].index.to_list()

In [12]:
condicion = pd.DataFrame(index = estreses.index)

condicion.loc[indicadores['control'] | indicadores['ctrl'], 'condicion'] = 'control'
control = condicion['condicion'] == 'control'

condicion.loc[~control, 'condicion'] = indicadores[~control].apply(cols_true, axis = 1)
condicion

              condicion
biosample
SAMD00133783    control
SAMD00133784  [drought]
SAMD00133785    control
SAMD00133786  [drought]
SAMD00133787    control
...                 ...
SAMN40876398    control
SAMN40876399    control
SAMN40876400   [stress]
SAMN40876401   [stress]
SAMN40876402   [stress]

[1574 rows x 1 columns]

In [13]:
multi = ~control & (condicion.loc[~control, 'condicion'].map(len) > 1)
condicion[multi]

                           condicion
biosample
SAMD00222779  [inoculated, pathogen]
SAMN03755595       [stress, deficit]
SAMN03755596       [stress, deficit]
SAMN03755597       [stress, deficit]
SAMN03755601       [stress, deficit]
...                              ...
SAMN38032658       [stress, drought]
SAMN38032659       [stress, drought]
SAMN38032660       [stress, drought]
SAMN38032661       [stress, drought]
SAMN38032662       [stress, drought]

[100 rows x 1 columns]

Muchas muestras tienen stress además del estrés específico. Me quedo con este último.

In [14]:
condicion.loc[multi, 'condicion'] = condicion.loc[multi, 'condicion'].apply(lambda r: [s for s in r if s != 'stress'], axis=1)
condicion[multi]

                           condicion
biosample
SAMD00222779  [inoculated, pathogen]
SAMN03755595               [deficit]
SAMN03755596               [deficit]
SAMN03755597               [deficit]
SAMN03755601               [deficit]
...                              ...
SAMN38032658               [drought]
SAMN38032659               [drought]
SAMN38032660               [drought]
SAMN38032661               [drought]
SAMN38032662               [drought]

[100 rows x 1 columns]

Repito a ver cuales quedaron con varios estreses

In [15]:
multi = ~control & (condicion.loc[~control, 'condicion'].map(len) > 1)
condicion[multi]

                           condicion
biosample
SAMD00222779  [inoculated, pathogen]
SAMN08469975  [inoculated, pathogen]
SAMN08469977  [inoculated, pathogen]
SAMN09295122      [inoculated, fung]
SAMN09295123      [inoculated, fung]
SAMN09295124      [inoculated, fung]
SAMN09295128      [inoculated, fung]
SAMN09295129      [inoculated, fung]
SAMN09295130      [inoculated, fung]
SAMN36630190         [deficit, acid]
SAMN36630191         [deficit, acid]
SAMN36630192         [deficit, acid]
SAMN36630193         [deficit, acid]
SAMN36630194         [deficit, acid]
SAMN36630195         [deficit, acid]
SAMN36630196         [deficit, acid]
SAMN36630197         [deficit, acid]
SAMN36630198         [deficit, acid]
SAMN36630205         [deficit, acid]
SAMN36630206         [deficit, acid]
SAMN36630207         [deficit, acid]
SAMN36630214         [deficit, acid]
SAMN36630215         [deficit, acid]
SAMN36630216         [deficit, acid]
SAMN36630244         [deficit, acid]
SAMN36630245         [deficit, acid]
SAMN36630246         [deficit, acid]
SAMN36630247         [deficit, acid]
SAMN36630248         [deficit, acid]
SAMN36630249         [deficit, acid]
SAMN36630250         [deficit, acid]
SAMN36630251         [deficit, acid]
SAMN36630252         [deficit, acid]
SAMN36630259         [deficit, acid]
SAMN36630260         [deficit, acid]
SAMN36630261         [deficit, acid]
SAMN36630268         [deficit, acid]
SAMN36630269         [deficit, acid]
SAMN36630270         [deficit, acid]

In [16]:
condicion.loc[multi, 'condicion'] = condicion.loc[multi, 'condicion'].apply(lambda r: [s for s in r if s != 'deficit' and s != 'inoculated'], axis=1)
condicion[multi]

               condicion
biosample
SAMD00222779  [pathogen]
SAMN08469975  [pathogen]
SAMN08469977  [pathogen]
SAMN09295122      [fung]
SAMN09295123      [fung]
SAMN09295124      [fung]
SAMN09295128      [fung]
SAMN09295129      [fung]
SAMN09295130      [fung]
SAMN36630190      [acid]
SAMN36630191      [acid]
SAMN36630192      [acid]
SAMN36630193      [acid]
SAMN36630194      [acid]
SAMN36630195      [acid]
SAMN36630196      [acid]
SAMN36630197      [acid]
SAMN36630198      [acid]
SAMN36630205      [acid]
SAMN36630206      [acid]
SAMN36630207      [acid]
SAMN36630214      [acid]
SAMN36630215      [acid]
SAMN36630216      [acid]
SAMN36630244      [acid]
SAMN36630245      [acid]
SAMN36630246      [acid]
SAMN36630247      [acid]
SAMN36630248      [acid]
SAMN36630249      [acid]
SAMN36630250      [acid]
SAMN36630251      [acid]
SAMN36630252      [acid]
SAMN36630259      [acid]
SAMN36630260      [acid]
SAMN36630261      [acid]
SAMN36630268      [acid]
SAMN36630269      [acid]
SAMN36630270      [acid]

Ahora los transformo a ```str```

In [27]:
isinstance(condicion.iloc[1,0], list)

True

In [19]:
condicion.to_csv('condicion.csv')