In [1]:
import pandas as pd

In [2]:
sra = pd.read_csv('../metadata/sra.csv', index_col=0)
biosamp = pd.read_csv('../metadata/biosample.csv', index_col=0)

/tmp/ipykernel_30577/1863096389.py:1: DtypeWarning: Columns (60,69,72,78,95,96,97,103,104,105,109,112,116,121,122,132,133,138,139,141,145,146,147,161,166,167,169,170,171,173,174,176,177,179,180,186,187,188,189,190,191,192,193,194,195,196,197,199,200,201,202,203,204,205,207,212,213,218,219,220,222,224,225,226,227,228,229,230,231,232,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266) have mixed types. Specify dtype option on import or set low_memory=False.
  sra = pd.read_csv('../metadata/sra.csv', index_col=0)
/tmp/ipykernel_30577/1863096389.py:2: DtypeWarning: Columns (27,31,63,64,66,85,87,88,89,92,93) have mixed types. Specify dtype option on import or set low_memory=False.
  biosamp = pd.read_csv('../metadata/biosample.csv', index_col=0)

In [3]:
metadata = sra.join(biosamp, rsuffix='_biosamp')
metadata

,acc,assay_type,center_name,consent,experiment,sample_name,instrument,librarylayout,libraryselection,librarysource,...,barcodesequence,scientific_name,BioSample,GSS,Sample name,SRA,GEO,DOE Joint Genome Institute,EST,SCN
biosample,,,,,,,,,,,,,,,,,,,,,
SAMD00235537,DRR237204,RNA-Seq,RIKEN_CSRS,public,DRX227388,SAMD00235537,Illumina HiSeq 2500,PAIRED,PolyA,TRANSCRIPTOMIC,...,NaN,NaN,SAMN00235537,LIBGSS_024689,NaN,NaN,NaN,NaN,NaN,NaN
SAMN30889879,SRR21660183,RNA-Seq,INNER MONGOLIA ACADEMY OF AGRICULTURAL & ANIMA...,public,SRX17659913,"CK (1,2,3,4)",Illumina NovaSeq 6000,PAIRED,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,SAMN30889879,NaN,"CK (1,2,3,4)",SRS15192176,NaN,NaN,NaN,NaN
SAMN09513405,SRR7447776,RNA-Seq,THE OHIO STATE UNIVERSITY,public,SRX4318240,SL209648,Illumina HiSeq 2500,PAIRED,PolyA,TRANSCRIPTOMIC,...,NaN,NaN,SAMN09513405,NaN,SL209648,SRS3480825,NaN,NaN,NaN,NaN
SAMN09078292,SRR7124263,RNA-Seq,GEO,public,SRX4045331,GSM3132253,Illumina HiSeq 2000,SINGLE,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,SAMN09078292,NaN,NaN,SRS3262752,GSM3132253,NaN,NaN,NaN
SAMN36760700,SRR25459671,RNA-Seq,SOYBEAN,public,SRX21192507,R89-2-1,Illumina HiSeq 4000,PAIRED,PCR,TRANSCRIPTOMIC,...,NaN,NaN,SAMN36760700,NaN,R89-2-1,SRS18451534,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAMN25827181,SRR17968854,RNA-Seq,HUAZHONG AGRICULTURAL UNIVERSITY,public,SRX14125189,II-Early-12dpi-2C_rep2,Illumina HiSeq 4000,PAIRED,Oligo-dT,TRANSCRIPTOMIC,...,NaN,NaN,SAMN25827181,NaN,II-Early-12dpi-2C_rep2,SRS11952324,NaN,NaN,NaN,NaN
SAMN20971793,SRR15610895,RNA-Seq,GEO,public,SRX11908208,GSM5536784,AB SOLiD System 3.0,PAIRED,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,SAMN20971793,NaN,NaN,SRS9919099,GSM5536784,NaN,NaN,NaN
SAMN41726398,SRR29315715,RNA-Seq,NORTHEAST AGRICULTURAL UNIVERSITY,public,SRX24832506,HPHO_MM_2,Illumina HiSeq 2000,PAIRED,RT-PCR,TRANSCRIPTOMIC,...,NaN,NaN,SAMN41726398,NaN,HPHO_MM_2,SRS21544452,NaN,NaN,NaN,NaN
SAMN07202264,SRR5655591,RNA-Seq,GEO,public,SRX2892180,GSM2651534,Illumina HiSeq 2500,PAIRED,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,SAMN07202264,NaN,NaN,SRS2259940,GSM2651534,NaN,NaN,NaN
SAMN09716352,SRR7592877,RNA-Seq,GEO,public,SRX4457873,GSM3306085,Illumina HiSeq 4000,SINGLE,cDNA,TRANSCRIPTOMIC,...,NaN,NaN,SAMN09716352,NaN,NaN,SRS3595413,GSM3306085,NaN,NaN,NaN

# Anotaciones

In [4]:
def matching_cols(row, pat):
    return row[row.astype(str).str.contains(pat, regex=False, case=False).fillna(False)].to_dict()

Junto palabras clave en kws. Guardo ```{columna: valor}``` en ```estreses``` si la columna contiene la palabra clave en su valor.

## Estreses

In [5]:
kws = ['control', 'ctrl', 'stress', 'drought', 'bacteria', 'inoculated', 'flood', 'deficit', 'infest', 'pathogen', 'acid', 'fung', 'sporus', 'iron', 'aluminum', 'cadmium', 'cold', 'temperature', 'nitrogen', 'heat']
estreses = pd.DataFrame(index = metadata.index)

for kw in kws:
    estreses[kw] = metadata.apply(lambda r: matching_cols(r, kw), axis=1)

In [6]:
ind_estr = estreses.map(lambda v: v != {})
ind_estr

,control,ctrl,stress,drought,bacteria,inoculated,flood,deficit,infest,pathogen,acid,fung,sporus,iron,aluminum,cadmium,cold,temperature,nitrogen,heat
biosample,,,,,,,,,,,,,,,,,,,,
SAMD00235537,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN30889879,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN09513405,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN09078292,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN36760700,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAMN25827181,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN20971793,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN41726398,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN07202264,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN09716352,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
ind_estr.sum(axis=0)

control        441
ctrl            13
stress         485
drought         84
bacteria         0
inoculated     339
flood            0
deficit        135
infest         141
pathogen         3
acid            79
fung             0
sporus           9
iron           358
aluminum         0
cadmium         12
cold            23
temperature    110
nitrogen        12
heat            82
dtype: int64

In [8]:
ind_estr.sum(axis=1)

biosample
SAMD00235537    0
SAMN30889879    0
SAMN09513405    1
SAMN09078292    0
SAMN36760700    1
               ..
SAMN25827181    0
SAMN20971793    1
SAMN41726398    0
SAMN07202264    0
SAMN09716352    0
Length: 10992, dtype: int64

In [9]:
estreses = estreses[ind_estr.sum(axis=1) > 0]
ind_estr = ind_estr.loc[estreses.index]
estreses.to_csv('estreses.csv')

## Tejidos

In [10]:
kws = ['leave', 'leaf', 'seed', 'crown', 'shoot', 'stem', 'hypocotyl', 'pod', 'root', 'embryo', 'cotyledon', 'petiole', 'radicle', 'root', 'ovule', 'ovary', 'embryo']
tejidos = pd.DataFrame(index = metadata.index)

for kw in kws:
    tejidos[kw] = metadata[['tissue_sam_ss_dpl145', 'tissue']].map(lambda c: str(c).replace('system', '')).apply(lambda r: matching_cols(r, kw), axis=1)

In [11]:
ind_teji = tejidos.map(lambda v: v!= {})
ind_teji

,leave,leaf,seed,crown,shoot,stem,hypocotyl,pod,root,embryo,cotyledon,petiole,radicle,ovule,ovary
biosample,,,,,,,,,,,,,,,
SAMD00235537,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN30889879,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
SAMN09513405,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
SAMN09078292,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN36760700,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAMN25827181,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
SAMN20971793,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN41726398,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
SAMN07202264,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
SAMN09716352,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False

In [12]:
ind_teji.sum(axis=0)

leave         853
leaf         1843
seed         2371
crown         202
shoot         992
stem          331
hypocotyl     102
pod           160
root         2001
embryo        229
cotyledon     116
petiole        21
radicle        15
ovule          33
ovary          22
dtype: int64

In [13]:
ind_teji.sum(axis=1)

biosample
SAMD00235537    0
SAMN30889879    1
SAMN09513405    1
SAMN09078292    1
SAMN36760700    1
               ..
SAMN25827181    1
SAMN20971793    0
SAMN41726398    1
SAMN07202264    1
SAMN09716352    1
Length: 10992, dtype: int64

In [14]:
tejidos = tejidos[ind_teji.sum(axis=1) > 0]
ind_teji = ind_teji.loc[tejidos.index]
tejidos.to_csv('tejidos.csv')

# Condicion

In [15]:
def cols_true(row):
# Devuelve lista de columnas verdaderas para row
    return row[row].index.to_list()

In [16]:
condicion = pd.DataFrame(index=tejidos.index.union(estreses.index))
condicion

Empty DataFrame
Columns: []
Index: [SAMD00133783, SAMD00133784, SAMD00133785, SAMD00133786, SAMD00133787, SAMD00133788, SAMD00161792, SAMD00161793, SAMD00161794, SAMD00161795, SAMD00161796, SAMD00161797, SAMD00161798, SAMD00161799, SAMD00182787, SAMD00182788, SAMD00182789, SAMD00182790, SAMD00183603, SAMD00183604, SAMD00183605, SAMD00183611, SAMD00222772, SAMD00222773, SAMD00222774, SAMD00222775, SAMD00222776, SAMD00222777, SAMD00222778, SAMD00222779, SAMD00222780, SAMD00235524, SAMD00235525, SAMD00235526, SAMD00235527, SAMD00235528, SAMD00235529, SAMD00235530, SAMD00235531, SAMD00235539, SAMD00235540, SAMD00235541, SAMD00235542, SAMD00235543, SAMD00235544, SAMD00235545, SAMD00235546, SAMD00235547, SAMD00549638, SAMD00549639, SAMD00549640, SAMD00549641, SAMD00549642, SAMD00549643, SAMD00549644, SAMD00549645, SAMD00549646, SAMD00549647, SAMD00549648, SAMD00549649, SAMD00549650, SAMD00549651, SAMD00549652, SAMD00549653, SAMD00549654, SAMD00549655, SAMD00549656, SAMD00549657, SAMD00549658, SAMD00549659, SAMD00549660, SAMD00549661, SAMD00549662, SAMD00549663, SAMD00549664, SAMD00549665, SAMD00549666, SAMD00549667, SAMD00549668, SAMD00549669, SAMD00549670, SAMD00549671, SAMD00549672, SAMD00549673, SAMD00549674, SAMD00549675, SAMEA5071870, SAMEA5071871, SAMEA5071872, SAMEA5071873, SAMEA5071880, SAMN00010675, SAMN00010676, SAMN00013424, SAMN00264986, SAMN00264987, SAMN00264988, SAMN00264989, SAMN00265076, SAMN00265078, ...]

[9448 rows x 0 columns]

## Estrés

In [17]:
ind_estr[ind_estr['control'] | ind_estr['ctrl']].index

Index(['SAMN09987958', 'SAMN05580232', 'SAMN29494544', 'SAMN20475803',
       'SAMN09489359', 'SAMN27616106', 'SAMN31760300', 'SAMN03797939',
       'SAMN03406695', 'SAMD00161793',
       ...
       'SAMN15350929', 'SAMN37004685', 'SAMN15456423', 'SAMN02597102',
       'SAMN30722352', 'SAMN05908882', 'SAMN05908875', 'SAMN29914733',
       'SAMN15350930', 'SAMN36630242'],
      dtype='object', name='biosample', length=454)

In [18]:
condicion.loc[ind_estr[ind_estr['control'] | ind_estr['ctrl']].index, 'estres'] = 'control'

In [19]:
bioprojects = pd.read_csv('../metadata/venancio.csv', index_col=0)
bioprojects[bioprojects['stress'] == 'control']

,stress,n,part,title,abstract,doi,pmid
bioproject,,,,,,,
PRJNA250761,control,1,unknown: 1,Glycine max strain:williams82 Transcriptome or...,JGI Flagship Plant Gene Atlas,NaN,NaN
PRJNA251047,control,1,unknown: 1,Glycine max strain:Williams 82 Transcriptome o...,JGI Flagship Plant Gene Atlas,NaN,NaN
PRJNA271453,control,3,leaf: 2 | root: 1,Glycine max Transcriptome or Gene expression,Transcriptome sequencing of Glycine max C08,NaN,NaN
PRJNA271506,control,2,flower: 2,Glycine max Transcriptome or Gene expression,soybean Transcriptome or Gene expression,NaN,NaN
PRJNA339653,control,4,leaf: 4,Glycine max Raw sequence reads,RNA-seq of soybean accessions,NaN,NaN
...,...,...,...,...,...,...,...
PRJNA668549,control,8,leaf: 8,Soybean Transcriptome (clean reads),Discover SMV-resistance genes/networks in soyb...,NaN,NaN
PRJNA758180,control,1,hypocotyl: 1,Glycine max Raw sequence reads,Glycine max RNA-seq reads,NaN,NaN
PRJNA801060,control,18,seed: 18,Glycine max Raw sequence reads,normal RNA-Seq of soybean seeds,NaN,NaN
PRJNA389558,control,102,leaf: 102,Transcriptomes of 102 soybean accessions,A comparison of RNA expression profiles across...,NaN,NaN
PRJNA692674,control,6,leaf: 6,RNAseq analysis of pooled soybean leaf samples...,Leaf samples were collected from soybean produ...,NaN,NaN

In [20]:
sample_stress_project = metadata.reset_index().set_index('bioproject').join(bioprojects, rsuffix='_bioprj').set_index('biosample')['stress']
condicion.loc[sample_stress_project == 'control', 'estres'] = 'control'

In [21]:
control = condicion['estres'] == 'control'

In [22]:
condicion.loc[~control, 'estres'] = ind_estr[~control].apply(cols_true, axis = 1)
condicion

/tmp/ipykernel_30577/2189651995.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  condicion.loc[~control, 'estres'] = ind_estr[~control].apply(cols_true, axis = 1)

                 estres
biosample
SAMD00133783    control
SAMD00133784  [drought]
SAMD00133785    control
SAMD00133786  [drought]
SAMD00133787    control
...                 ...
SAMN41829221        NaN
SAMN41829222        NaN
SAMN41829223        NaN
SAMN41829224        NaN
SAMN41829225        NaN

[9448 rows x 1 columns]

In [23]:
lista = condicion['estres'].apply(lambda r: isinstance(r, list))
lista

biosample
SAMD00133783    False
SAMD00133784     True
SAMD00133785    False
SAMD00133786     True
SAMD00133787    False
                ...
SAMN41829221    False
SAMN41829222    False
SAMN41829223    False
SAMN41829224    False
SAMN41829225    False
Name: estres, Length: 9448, dtype: bool

In [24]:
multi = ~control & (condicion.loc[~control & lista, 'estres'].map(len) > 1)
condicion[multi]

                                estres
biosample
SAMD00222772  [stress, cold, nitrogen]
SAMD00222775    [inoculated, nitrogen]
SAMD00222776    [inoculated, nitrogen]
SAMD00222777    [inoculated, nitrogen]
SAMD00222778    [inoculated, nitrogen]
...                                ...
SAMN38032658         [stress, drought]
SAMN38032659         [stress, drought]
SAMN38032660         [stress, drought]
SAMN38032661         [stress, drought]
SAMN38032662         [stress, drought]

[412 rows x 1 columns]

Muchas muestras tienen stress además del estrés específico. Me quedo con este último.

In [25]:
condicion.loc[multi, 'estres'] = condicion.loc[multi, 'estres'].apply(lambda r: [s for s in r if s != 'stress'])
condicion[multi]

                              estres
biosample
SAMD00222772        [cold, nitrogen]
SAMD00222775  [inoculated, nitrogen]
SAMD00222776  [inoculated, nitrogen]
SAMD00222777  [inoculated, nitrogen]
SAMD00222778  [inoculated, nitrogen]
...                              ...
SAMN38032658               [drought]
SAMN38032659               [drought]
SAMN38032660               [drought]
SAMN38032661               [drought]
SAMN38032662               [drought]

[412 rows x 1 columns]

Repito a ver cuales quedaron con varios estreses

In [26]:
multi = ~control & (condicion.loc[~control & lista, 'estres'].map(len) > 1)
condicion[multi]

                                        estres
biosample
SAMD00222772                  [cold, nitrogen]
SAMD00222775            [inoculated, nitrogen]
SAMD00222776            [inoculated, nitrogen]
SAMD00222777            [inoculated, nitrogen]
SAMD00222778            [inoculated, nitrogen]
SAMD00222779  [inoculated, pathogen, nitrogen]
SAMD00222780            [inoculated, nitrogen]
SAMN08469975            [inoculated, pathogen]
SAMN08469977            [inoculated, pathogen]
SAMN22481313                   [deficit, heat]
SAMN22481314                   [deficit, heat]
SAMN22481315                   [deficit, heat]
SAMN30876642                   [deficit, heat]
SAMN30876643                   [deficit, heat]
SAMN30876644                   [deficit, heat]
SAMN31760278                   [deficit, heat]
SAMN31760279                   [deficit, heat]
SAMN31760280                   [deficit, heat]
SAMN31760290                   [deficit, heat]
SAMN31760291                   [deficit, heat]
SAMN31760292                   [deficit, heat]
SAMN31760302                   [deficit, heat]
SAMN31760303                   [deficit, heat]
SAMN31760304                   [deficit, heat]
SAMN31760314                   [deficit, heat]
SAMN31760315                   [deficit, heat]
SAMN31760316                   [deficit, heat]
SAMN36630190          [deficit, acid, cadmium]
SAMN36630191          [deficit, acid, cadmium]
SAMN36630192          [deficit, acid, cadmium]
SAMN36630193                   [deficit, acid]
SAMN36630194                   [deficit, acid]
SAMN36630195                   [deficit, acid]
SAMN36630196                   [deficit, acid]
SAMN36630197                   [deficit, acid]
SAMN36630198                   [deficit, acid]
SAMN36630205                   [deficit, acid]
SAMN36630206                   [deficit, acid]
SAMN36630207                   [deficit, acid]
SAMN36630214                   [deficit, acid]
SAMN36630215                   [deficit, acid]
SAMN36630216                   [deficit, acid]
SAMN36630244          [deficit, acid, cadmium]
SAMN36630245          [deficit, acid, cadmium]
SAMN36630246          [deficit, acid, cadmium]
SAMN36630247                   [deficit, acid]
SAMN36630248                   [deficit, acid]
SAMN36630249                   [deficit, acid]
SAMN36630250                   [deficit, acid]
SAMN36630251                   [deficit, acid]
SAMN36630252                   [deficit, acid]
SAMN36630259                   [deficit, acid]
SAMN36630260                   [deficit, acid]
SAMN36630261                   [deficit, acid]
SAMN36630268                   [deficit, acid]
SAMN36630269                   [deficit, acid]
SAMN36630270                   [deficit, acid]

In [27]:
condicion.loc[multi, 'estres'] = condicion.loc[multi, 'estres'].apply(lambda r: [s for s in r if s != 'deficit' and s != 'inoculated'])
condicion[multi]

                            estres
biosample
SAMD00222772      [cold, nitrogen]
SAMD00222775            [nitrogen]
SAMD00222776            [nitrogen]
SAMD00222777            [nitrogen]
SAMD00222778            [nitrogen]
SAMD00222779  [pathogen, nitrogen]
SAMD00222780            [nitrogen]
SAMN08469975            [pathogen]
SAMN08469977            [pathogen]
SAMN22481313                [heat]
SAMN22481314                [heat]
SAMN22481315                [heat]
SAMN30876642                [heat]
SAMN30876643                [heat]
SAMN30876644                [heat]
SAMN31760278                [heat]
SAMN31760279                [heat]
SAMN31760280                [heat]
SAMN31760290                [heat]
SAMN31760291                [heat]
SAMN31760292                [heat]
SAMN31760302                [heat]
SAMN31760303                [heat]
SAMN31760304                [heat]
SAMN31760314                [heat]
SAMN31760315                [heat]
SAMN31760316                [heat]
SAMN36630190       [acid, cadmium]
SAMN36630191       [acid, cadmium]
SAMN36630192       [acid, cadmium]
SAMN36630193                [acid]
SAMN36630194                [acid]
SAMN36630195                [acid]
SAMN36630196                [acid]
SAMN36630197                [acid]
SAMN36630198                [acid]
SAMN36630205                [acid]
SAMN36630206                [acid]
SAMN36630207                [acid]
SAMN36630214                [acid]
SAMN36630215                [acid]
SAMN36630216                [acid]
SAMN36630244       [acid, cadmium]
SAMN36630245       [acid, cadmium]
SAMN36630246       [acid, cadmium]
SAMN36630247                [acid]
SAMN36630248                [acid]
SAMN36630249                [acid]
SAMN36630250                [acid]
SAMN36630251                [acid]
SAMN36630252                [acid]
SAMN36630259                [acid]
SAMN36630260                [acid]
SAMN36630261                [acid]
SAMN36630268                [acid]
SAMN36630269                [acid]
SAMN36630270                [acid]

Ahora los transformo a ```str```

In [28]:
condicion.loc[lista, 'estres'] = condicion.loc[lista, 'estres'].apply(lambda r: r[0])

## Tejido

In [29]:
condicion.loc[ind_teji.index, 'tejido'] = ind_teji.apply(cols_true, axis=1)
condicion.loc[ind_teji.index, 'tejido'] = condicion.loc[(ind_teji.sum(axis=1) > 0).index, 'tejido']
ind_teji = ind_teji.loc[tejidos.index]
tejidos

,leave,leaf,seed,crown,shoot,stem,hypocotyl,pod,root,embryo,cotyledon,petiole,radicle,ovule,ovary
biosample,,,,,,,,,,,,,,,
SAMN30889879,{},{},{},{},{},{},{},{},"{'tissue_sam_ss_dpl145': 'Root', 'tissue': 'Ro...",{},{},{},{},{},{}
SAMN09513405,{},{},{},{'tissue_sam_ss_dpl145': 'inoculation site: ~2...,{},{},{},{},{},{},{},{},{},{},{}
SAMN09078292,{},"{'tissue_sam_ss_dpl145': 'leaf', 'tissue': 'le...",{},{},{},{},{},{},{},{},{},{},{},{},{}
SAMN36760700,{},{},{},{},{},{},{},{},{},"{'tissue_sam_ss_dpl145': 'Embryo', 'tissue': '...",{},{},{},{},{}
SAMN41725164,{},{},"{'tissue_sam_ss_dpl145': 'seed', 'tissue': 'se...",{},{},{},{},{},{},{},{},{},{},{},{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAMN32153785,{},{},"{'tissue_sam_ss_dpl145': 'seed', 'tissue': 'se...",{},{},{},{},{},{},{},{},{},{},{},{}
SAMN25827181,{},{},{},{},{},{},{},{},"{'tissue_sam_ss_dpl145': 'root nodules', 'tiss...",{},{},{},{},{},{}
SAMN41726398,{},{},"{'tissue_sam_ss_dpl145': 'seed', 'tissue': 'se...",{},{},{},{},{},{},{},{},{},{},{},{}
SAMN07202264,"{'tissue_sam_ss_dpl145': 'leaves', 'tissue': '...",{},{},{},{},{},{},{},{},{},{},{},{},{},{}
SAMN09716352,{},{},{},{},{'tissue_sam_ss_dpl145': 'The whole shoot abov...,{},{},{},{},{},{},{},{},{},{}

In [30]:
multi = (ind_teji.sum(axis=1) > 1).index
condicion.loc[multi, 'tejido'] = condicion.loc[multi, 'tejido'].apply(lambda r: [t for t in r if t != 'stem'] if 'stem' in r and len(r) > 1 else r)

In [31]:
condicion.loc[multi, 'tejido'] = condicion.loc[multi, 'tejido'].apply(lambda r: 'whole' if ('leave' in r or 'leaf' in r) and 'root' in r else r)
condicion.loc[multi, 'tejido'] = condicion.loc[multi, 'tejido'].apply(lambda r: [t for t in r if t != 'stem'] if 'stem' in r and len(r) > 1 else r)
condicion.loc[multi, 'tejido'] = condicion.loc[multi, 'tejido'].apply(lambda r: 'seed' if 'seed' in r else r)
condicion.loc[multi, 'tejido'] = condicion.loc[multi, 'tejido'].apply(lambda r: 'root' if 'root' in r else r)
condicion.loc[multi, 'tejido'] = condicion.loc[multi, 'tejido'].apply(lambda r: 'cotyledon' if 'cotyledon' in r else r)
condicion.loc[multi]

                   estres    tejido
biosample
SAMN30889879          NaN      root
SAMN09513405   inoculated   [crown]
SAMN09078292          NaN    [leaf]
SAMN36760700  temperature  [embryo]
SAMN41725164          NaN      seed
...                   ...       ...
SAMN32153785          NaN      seed
SAMN25827181          NaN      root
SAMN41726398          NaN      seed
SAMN07202264      control   [leave]
SAMN09716352          NaN   [shoot]

[9098 rows x 2 columns]

In [32]:
lista = condicion['tejido'].apply(lambda r: isinstance(r, list))
condicion.loc[lista, 'tejido'] = condicion.loc[lista, 'tejido'].apply(lambda r: r[0])
condicion

               estres tejido
biosample
SAMD00133783  control    NaN
SAMD00133784  drought    NaN
SAMD00133785  control    NaN
SAMD00133786  drought    NaN
SAMD00133787  control    NaN
...               ...    ...
SAMN41829221      NaN   stem
SAMN41829222      NaN   stem
SAMN41829223      NaN   stem
SAMN41829224      NaN   stem
SAMN41829225      NaN   stem

[9448 rows x 2 columns]

In [33]:
condicion.to_csv('condicion.csv')